apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimda
  labels:
    app: nimda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimda
  template:
    metadata:
      labels:
        app: nimda
    spec:
      containers:
        - name: nimda
          image: 185813569261.dkr.ecr.us-east-2.amazonaws.com/nimda:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
